version: '2'

services:
  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile - 
      --reload
      "pets_api.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/pets_api'
    ports:
     - '8000:8000'
    container_name: petsapi_web_1
    depends_on:
      - db
  
  db:
    image: mongo:3.0.2
    container_name: petsapi_db_1
